#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: pastiches
    username: admin
    realname: Admin
    # Replace with a hash of your password
    # mkpasswd --method=SHA-512
    password: "$6$yDTp9gldoo3E0k96$4.MtdLIDE.9oKU6O387yfN/6tDISjf/i0I70PoFL/JJF/j/QbzdGU8BQl5w/onKVxYFVv2WRsPQtwZoT9Ou/r."
  storage:
    layout:
      name: lvm
  network:
    network:
      version: 2
      ethernets:
        all-eths:
          match:
            name: "en*"
          dhcp4: true
  ssh:
    install-server: yes
  updates: all
  shutdown: poweroff

  keyboard:
    layout: us
  locale: en_US
  timezone: America/New_York

  packages:
    # Core dev packages
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
    - ca-certificates
    - gedit
    - git
    - python3-pip
    - python3-venv
    - gnupg
    - net-tools
    
    # Docker stuff
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

    # For ansible
    - ansible
    - python3-docker

  late-commands:
#    # Clone repos to use here
#    - curtin in-target -- mkdir -p /opt/repos
#    - curtin in-target -- git clone https://github.com/dasheath/ansible-setup.git /opt/repos/ansible-setup

#    # Clone your Ansible repo and run ansible-pull
#    - curtin in-target -- su - admin -c "ansible-pull -U https://github.com/dasheath/ansible-setup.git site.yml"

    # Optional: add admin user to sudoers with no password
    - curtin in-target -- bash -c 'echo "%sudo ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-nopasswd && chmod 440 /etc/sudoers.d/90-nopasswd'

