- name: Clone dotfiles repo for each user
  become: true
  become_user: "{{ item.name }}"
  git:
    repo: "{{ dotfiles_repo_map[clone_with | default('https')] }}"
    dest: "/home/{{ item.name }}/dotfiles"
    version: "{{ dotfiles_branch }}"
    update: yes
  loop: "{{ managed_users }}"

- name: Install stow command
  apt:
    name: 
      - stow
    state: present

- name: Stow dotfiles directory for each user
  become: true
  become_user: "{{ item.name }}"
  ansible.builtin.shell:
    cmd: stow --verbose .
    chdir: "/home/{{ item.name }}/dotfiles"
  loop: "{{ managed_users }}"

